### ISSUE TITLE
Optimize usage for troubleshooting

### ISSUE THREAD

**Issue by InappropriatePenguin** [raiguard/factorio_mod_manager#1]
My apologies if this is outside the scope of this tool or if it's even already possible. I just thought of a cool use case and I wonder if it might be worth considering.

`fmm --troubleshoot path/to/save.zip`

The config file would include the path to a temporary mods folder that is used specifically for troubleshooting save files. Rather than download all the savefile's mods to that folder, the regular mods folder would be checked to see if it has any of the named mods. If it does, they'd be either copied (or preferably symlinked) from there to the temporary mods folder. It would then start the game with the savefile's settings using temporary mods folder as the modpath.

What to do with the downloaded mods after troubleshooting is done, I'm not sure. It would theoretically be nice to be able to move them to some archive mods folder so that they don't have to be re-downloaded again if the same mod/version is needed in the future.

**Comment by raiguard** [comment]
I'm finally at the point where I can consider this.

I'm not a huge fan of the idea of integrating the entire thing into fmm. This is the Factorio mod manager, and it doesn't have any control over the execution of Factorio itself. It seems to me like the best solution would be to create a shell script that would do the following:

- Create a temporary mods dir
- Invoke fmm passing the save to sync with, and passing the temporary dir to `--mods-dir`
- Start the game, passing the temporary mods dir and telling it to load the given file

As for pulling from the real mods directory instead of the portal, that would be something that fmm would have to handle. I'll look into it.
